---
apiVersion: v1
data:
  saToken: bWlzY29uZmlndXJlZC1zYS10b2tlbgo=
kind: Secret
metadata:
  name: source-cluster-secret
  namespace: openshift-config
type: Opaque
---
apiVersion: migration.openshift.io/v1alpha1
kind: MigCluster
metadata:
  name: source-cluster
  namespace: openshift-migration
spec:
  insecure: true
  isHostCluster: false
  serviceAccountSecretRef:
    name: source-cluster-secret
    namespace: openshift-config
  url: "https://misconfigured-url.com:443"
---
apiVersion: v1
data:
  aws-access-key-id: YXdzLWtleS1pZAo=
  aws-secret-access-key: YXdzLWFjY2Vzcy1rZXktaWQK
kind: Secret
metadata:
  name: s3-repository
  namespace: openshift-config
type: Opaque
---
apiVersion: migration.openshift.io/v1alpha1
kind: MigStorage
metadata:
  name: s3-repository
  namespace: openshift-migration
spec:
  backupStorageConfig:
    awsBucketName: non-existing-bucket
    credsSecretRef:
      name: s3-repository
      namespace: openshift-config
    insecure: true
  backupStorageProvider: aws
  volumeSnapshotConfig:
    credsSecretRef:
      name: s3-repository
      namespace: openshift-config
  volumeSnapshotProvider: aws
